version: '3.8'

services:
  pharmacold-db:
    image: postgres:15-alpine
    container_name: pharmacold_postgres
    restart: always
    environment:
      POSTGRES_DB: pharmacold_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5440:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5